/**
 * This package provides JDBC utilities for database operations, using codes similar to the following:
 * <pre>{@code
 * // Create a connection (you can also use a connection pool)
 * Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "user", "password");
 *
 * try {
 *     // Using SqlBuilder for fluent SQL construction
 *     PreparedSql sql = SqlBuilder.newBuilder()
 *         .append("SELECT * FROM users")
 *         .appendIf(searchEnabled, " WHERE name LIKE ?", "%" + searchTerm + "%")
 *         .append(" ORDER BY created_at DESC")
 *         .build()
 *         .connection(connection);
 *
 *     // Query with result mapping
 *     try (SqlQuery<User> query = sql.query(User.class)) {
 *         List<User> users = query.resultList();
 *         // Process users...
 *     }
 *
 *     // Update with affected rows
 *     try (SqlUpdate update = SqlBuilder.newBuilder()
 *         .append("UPDATE users SET status = ? WHERE id = ?", "ACTIVE", userId)
 *         .build()
 *         .connection(connection)
 *         .update()) {
 *         long affected = update.affectedRows();
 *     }
 *
 *     // Insert with auto-generated keys
 *     try (SqlInsert insert = SqlBuilder.newBuilder()
 *         .append("INSERT INTO users (name, email) VALUES (?, ?)", name, email)
 *         .build()
 *         .connection(connection)
 *         .insert()) {
 *         List<Object> keys = insert.autoGeneratedKeys();
 *     }
 * } finally {
 *     // Don't forget to close the connection
 *     if (connection != null) {
 *         connection.close();
 *     }
 * }
 * }</pre>
 * <p>
 * Core interfaces:
 * <ul>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlBuilder}: Fluent interface for building SQL statements programmatically</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.PreparedSql}: Represents a prepared SQL statement with parameter binding support</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlQuery}: Represents a SQL query operation with result mapping</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlUpdate}: Represents a SQL update operation</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlInsert}: Represents a SQL insert operation with auto-generated key support</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlResult}: Base interface for all SQL operations</li>
 * </ul>
 * <p>
 * Utility classes:
 * <ul>
 *     <li>{@link space.sunqian.fs.utils.jdbc.JdbcKit}: Utilities for converting ResultSet to objects</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.JdbcException}: Exception class for JDBC operations</li>
 * </ul>
 * <p>
 * Implementation classes:
 * <ul>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlBack}: Contains all implementation classes for the JDBC interfaces</li>
 * </ul>
 */
package space.sunqian.fs.utils.jdbc;