/**
 * This package provides JDBC utilities for database operations, using codes similar to the following:
 * <pre>{@code
 * // Using connection pool with JdbcClient
 * JdbcClient client = JdbcClient.newBuilder()
 *     .url("jdbc:mysql://localhost:3306/test")
 *     .username("root")
 *     .password("password")
 *     .coreSize(5)
 *     .maxSize(20)
 *     .idleTimeout(60000)
 *     .build();
 *
 * try (JdbcClient client = ...) {
 *     // Using SqlBuilder for fluent SQL construction
 *     SqlBuilder builder = client.newSqlBuilder();
 *     PreparedSql sql = builder
 *         .append("SELECT * FROM users")
 *         .appendIf(searchEnabled, " WHERE name LIKE ?", "%" + searchTerm + "%")
 *         .append(" ORDER BY created_at DESC")
 *         .build();
 *
 *     // Query with result mapping
 *     try (SqlQuery<User> query = sql.query(User.class)) {
 *         List<User> users = query.resultList();
 *         // Process users...
 *     }
 *
 *     // Update with affected rows
 *     try (SqlUpdate update = builder
 *         .append("UPDATE users SET status = ? WHERE id = ?", "ACTIVE", userId)
 *         .build()
 *         .update()) {
 *         long affected = update.affectedRows();
 *     }
 *
 *     // Insert with auto-generated keys
 *     try (SqlInsert insert = builder
 *         .append("INSERT INTO users (name, email) VALUES (?, ?)", name, email)
 *         .build()
 *         .insert()) {
 *         List<Object> keys = insert.autoGeneratedKeys();
 *     }
 * }
 * }</pre>
 * <p>
 * Core interfaces:
 * <ul>
 *     <li>{@link space.sunqian.fs.jdbc.JdbcClient}: JDBC client with connection pool support</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.PreparedSql}: Represents a prepared SQL statement with parameter binding support</li>
 *     <li>{@link space.sunqian.fs.jdbc.SqlBuilder}: Fluent interface for building SQL statements programmatically</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlQuery}: Represents a SQL query operation with result mapping</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlUpdate}: Represents a SQL update operation</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlInsert}: Represents a SQL insert operation with auto-generated key support</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.SqlOperation}: Base interface for all SQL operations</li>
 * </ul>
 * <p>
 * Utility classes:
 * <ul>
 *     <li>{@link space.sunqian.fs.utils.jdbc.JdbcKit}: Utilities for converting ResultSet to objects</li>
 *     <li>{@link space.sunqian.fs.utils.jdbc.JdbcException}: Exception class for JDBC operations</li>
 * </ul>
 * <p>
 * Implementation classes:
 * <ul>
 *     <li>{@link space.sunqian.fs.jdbc.JdbcClientImpl}: Implementation of JdbcClient using SimplePool</li>
 *     <li>{@link space.sunqian.fs.jdbc.PreparedSqlImpl}: Main implementation class containing all SQL operation implementations</li>
 *     <li>{@link space.sunqian.fs.jdbc.SqlBuilderImpl}: Implementation of SqlBuilder interface</li>
 * </ul>
 */
package space.sunqian.fs.utils.jdbc;