package space.sunqian.fs.utils.jdbc;

import space.sunqian.annotation.Immutable;
import space.sunqian.annotation.Nonnull;
import space.sunqian.fs.Fs;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 * This interface represents the insert result of a SQL execution.
 *
 * @author sunqian
 */
public interface SqlInsert extends SqlResult {

    /**
     * Returns the auto-generated keys of this SQL statement.
     *
     * @return the auto-generated keys of this SQL statement
     * @throws JdbcException if any error occurs
     */
    default @Nonnull @Immutable List<@Nonnull Object> autoGeneratedKeys() throws JdbcException {
        return Fs.uncheck(() -> {
            PreparedStatement statement = preparedStatement();
            // Get auto-generated keys
            ResultSet generatedKeys = statement.getGeneratedKeys();
            List<Object> keys = new ArrayList<>();
            while (generatedKeys.next()) {
                keys.add(generatedKeys.getObject(1));
            }
            generatedKeys.close();
            return keys;
        }, JdbcException::new);
    }

    /**
     * Returns the number of rows inserted by this SQL statement.
     *
     * @return the number of rows inserted by this SQL statement
     * @throws JdbcException if any error occurs
     */
    @SuppressWarnings("resource")
    default long insertedRows() throws JdbcException {
        return Fs.uncheck(() -> preparedStatement().getUpdateCount(), JdbcException::new);
    }
}
