package space.sunqian.fs.utils.jdbc;

import space.sunqian.annotation.Immutable;
import space.sunqian.annotation.Nonnull;

import java.util.List;

/**
 * This interface represents the insert result of a SQL execution.
 *
 * @author sunqian
 */
public interface SqlInsert extends SqlResult {

    /**
     * Returns the number of rows inserted by this SQL statement.
     *
     * @return the number of rows inserted by this SQL statement
     */
    long insertedRows();

    /**
     * Returns the auto-generated keys of this SQL statement.
     *
     * @return the auto-generated keys of this SQL statement
     */
    @Immutable
    @Nonnull
    List<@Nonnull Object> autoGeneratedKeys();
}
