package xyz.sunqian.common.net.tcp;

import xyz.sunqian.annotations.Nonnull;
import xyz.sunqian.annotations.Nullable;

import java.nio.ByteBuffer;

/**
 * Event listener for {@link TcpNetServer}.
 * <p>
 * Except for the {@link #onMessage(TcpNetEndpoint, ByteBuffer)}, which must be implemented, all other methods have
 * default empty methods.
 *
 * @author sunqian
 */
public interface TcpNetListener {

    /**
     * This method is invoked after the server has been started. It is the first invocation among all the listening
     * methods, and will only be invoked once.
     *
     * @throws Exception if any error occurs
     */
    default void onOpen() throws Exception {
    }

    /**
     * This method is invoked after the underlying server has been closed. It is the last invocation among all the
     * listening methods, and will only be invoked once.
     *
     * @throws Exception if any error occurs
     */
    default void onClose() throws Exception {
    }

    /**
     * This method is invoked when a new connection is established, and only invoked once for each new connection.
     *
     * @param endpoint the remote endpoint of the new connection
     * @throws Exception if any error occurs
     */
    default void onConnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
    }

    /**
     * This method is invoked when the remote endpoint disconnects, and only invoked once for each connection.
     *
     * @param endpoint the remote endpoint of the connection
     * @throws Exception if any error occurs
     */
    default void onDisconnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
    }

    /**
     * This method is invoked when an exception occurs. The exception may be an unhandled exception from other listener
     * methods, or generated by the server.
     *
     * @param server    the  server
     * @param endpoint  the remote endpoint, may be {@code null} if the exception is generated by the server
     * @param throwable the exception
     */
    default void onException(@Nonnull TcpNetServer server, @Nullable TcpNetEndpoint endpoint, Throwable throwable) {
    }

    /**
     * This method is invoked when a message is received.
     *
     * @param endpoint the remote endpoint
     * @param msg      the message
     * @throws Exception if any error occurs
     */
    void onMessage(@Nonnull TcpNetEndpoint endpoint, @Nonnull ByteBuffer msg) throws Exception;
}
