package xyz.sunqian.common.net.tcp;

import xyz.sunqian.annotations.Nonnull;
import xyz.sunqian.annotations.Nullable;
import xyz.sunqian.common.io.IOKit;
import xyz.sunqian.common.io.IOMode;
import xyz.sunqian.common.net.NetException;
import xyz.sunqian.common.net.NetOption;
import xyz.sunqian.common.net.NetServer;

import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.UnknownHostException;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executor;

/**
 * This interface represents a TCP/IP network server.
 *
 * @author sunqian
 */
public interface TcpNetServer extends NetServer<InetSocketAddress> {

    /**
     * Returns a new builder for generating {@link TcpNetServer}.
     */
    static @Nonnull Builder newBuilder() {
        return new Builder();
    }

    /**
     * Returns the port number to which this server is bound, may be {@code -1} if the server is not bound yet.
     *
     * @return the port number to which this server is bound, may be {@code -1} if the server is not bound yet
     */
    default int getBoundPort() {
        InetSocketAddress address = getBoundAddress();
        return address != null ? address.getPort() : -1;
    }

    /**
     * Returns the IP this server is bound to, may be {@code null} if the server is not bound yet.
     *
     * @return the IP this server is bound to, may be {@code null} if the server is not bound yet
     */
    default @Nullable InetAddress getBoundIp() {
        InetSocketAddress address = getBoundAddress();
        return address != null ? address.getAddress() : null;
    }

    /**
     * Event listener for {@link TcpNetServer}.
     * <p>
     * Except for the {@link #onMessage(TcpNetEndpoint, ByteBuffer)}, which must be implemented, all other methods have
     * default empty methods.
     *
     * @author sunqian
     */
    interface Listener {

        /**
         * This method is invoked after the server has been started. It is the first invocation among all the listening
         * methods, and will only be invoked once.
         *
         * @throws Exception if any error occurs
         */
        default void onOpen() throws Exception {
        }

        /**
         * This method is invoked after the underlying server has been closed. It is the last invocation among all the
         * listening methods, and will only be invoked once.
         *
         * @throws Exception if any error occurs
         */
        default void onClose() throws Exception {
        }

        /**
         * This method is invoked when a new connection is established, and only invoked once for each new connection.
         *
         * @param endpoint the remote endpoint of the new connection
         * @throws Exception if any error occurs
         */
        default void onConnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
        }

        /**
         * This method is invoked when the remote endpoint disconnects, and only invoked once for each connection.
         *
         * @param endpoint the remote endpoint of the connection
         * @throws Exception if any error occurs
         */
        default void onDisconnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
        }

        /**
         * This method is invoked when an exception occurs. The exception may be an unhandled exception from other
         * listener methods, or generated by the server.
         *
         * @param server    the  server
         * @param endpoint  the remote endpoint, may be {@code null} if the exception is generated by the server
         * @param throwable the exception
         */
        default void onException(@Nonnull TcpNetServer server, @Nullable TcpNetEndpoint endpoint, Throwable throwable) {
        }

        /**
         * This method is invoked when a message is received.
         *
         * @param endpoint the remote endpoint
         * @param msg      the message
         * @throws Exception if any error occurs
         */
        void onMessage(@Nonnull TcpNetEndpoint endpoint, @Nonnull ByteBuffer msg) throws Exception;
    }

    /**
     * Builder for creating new TCP/IP network server.
     *
     * @author sunqian
     */
    class Builder {

        private @Nullable Integer port;
        private @Nullable InetAddress ip;
        private int backlog = 50;
        private int bufSize = IOKit.bufferSize();
        private @Nullable Executor acceptExecutor;
        private @Nullable Executor workExecutor;
        private @Nullable List<@Nonnull NetOption<?>> options;
        private @Nullable Listener listener;
        private @Nonnull IOMode ioMode = IOMode.BLOCKING;

        /**
         * Sets the port number to which this server is bound.
         *
         * @param port the port number to which this server is bound
         * @return this
         */
        public Builder port(int port) {
            this.port = port;
            return this;
        }

        /**
         * Sets the IP this server is bound to.
         *
         * @param ip the IP this server is bound to
         * @return this
         */
        public Builder ip(@Nonnull InetAddress ip) {
            this.ip = ip;
            return this;
        }

        /**
         * Sets the IP, specified by the given host, to which this server is bound. The host can either be a hostname,
         * or a textual representation of its IP address.
         *
         * @param host the given host
         * @return this
         * @throws NetException if the IP can not be determined
         */
        public Builder host(@Nonnull String host) throws NetException {
            try {
                this.ip = InetAddress.getByName(host);
            } catch (UnknownHostException e) {
                throw new NetException(e);
            }
            return this;
        }

        /**
         * Sets the address this server is bound to.
         *
         * @param address the address this server is bound to
         * @return this
         */
        public Builder address(@Nonnull InetSocketAddress address) {
            this.port = address.getPort();
            this.ip = address.getAddress();
            return this;
        }

        /**
         * Sets requested maximum length of the queue of incoming connections
         *
         * @param backlog requested maximum length of the queue of incoming connections
         * @return this
         */
        public Builder backlog(int backlog) {
            this.backlog = backlog;
            return this;
        }

        /**
         * Adds a network option.
         *
         * @param option the network option
         * @return this
         */
        public Builder netOption(@Nonnull NetOption<?> option) {
            if (options == null) {
                options = new ArrayList<>();
            }
            options.add(option);
            return this;
        }

        /**
         * Sets the network listener to listen and handle the network events.
         *
         * @param listener the network listener
         * @return this
         */
        public Builder listener(@Nonnull Listener listener) {
            this.listener = listener;
            return this;
        }

        /**
         * Sets the executor responsible for handling accept events, which occur when the server accepts a new incoming
         * connection.
         *
         * @param acceptExecutor the executor responsible for handling accept events
         * @return this
         */
        public Builder acceptExecutor(@Nonnull Executor acceptExecutor) {
            this.acceptExecutor = acceptExecutor;
            return this;
        }

        /**
         * Sets the executor responsible for handling all non-accept server events.
         *
         * @param workExecutor the executor responsible for handling all non-accept server events
         * @return this
         */
        public Builder workExecutor(@Nonnull Executor workExecutor) {
            this.workExecutor = workExecutor;
            return this;
        }

        /**
         * Sets the buffer size for reading bytes from the remote endpoints. The default is {@link IOKit#bufferSize()}.
         *
         * @param bufSize the buffer size for reading bytes from the remote endpoints
         * @return this
         * @throws IllegalArgumentException if the buffer size is not positive
         */
        public Builder bufferSize(int bufSize) throws IllegalArgumentException {
            if (bufSize <= 0) {
                throw new IllegalArgumentException("buffer size must > 0.");
            }
            this.bufSize = bufSize;
            return this;
        }

        /**
         * Sets the I/O mode of the server. The default is {@link IOMode#BLOCKING}.
         *
         * @param ioMode the I/O mode of the server
         * @return this
         */
        public Builder ioMode(@Nonnull IOMode ioMode) {
            this.ioMode = ioMode;
            return this;
        }

        /**
         * Generates a new {@link TcpNetServer} with the current configurations.
         *
         * @return a new {@link TcpNetServer} with the current configurations
         * @throws NetException if an error occurs while creating the server
         */
        public @Nonnull TcpNetServer build() throws NetException {
            if (listener == null) {
                throw new NetException("listener is null.");
            }
            if (acceptExecutor == null) {
                throw new NetException("acceptExecutor is null.");
            }
            if (workExecutor == null) {
                throw new NetException("workExecutor is null.");
            }
            try {
                return ioMode.equals(IOMode.BLOCKING) ?
                    buildBlocking(listener, acceptExecutor, workExecutor)
                    :
                    buildNonBlocking(listener, acceptExecutor, workExecutor);
            } catch (Exception e) {
                throw new NetException(e);
            }
        }

        private @Nonnull TcpNetServer buildBlocking(
            @Nonnull Listener listener,
            @Nonnull Executor acceptExecutor,
            @Nonnull Executor workExecutor
        ) throws Exception {
            ServerSocket serverSocket;
            if (ip == null) {
                serverSocket = new ServerSocket(port == null ? 0 : port, backlog);
            } else {
                serverSocket = new ServerSocket(port == null ? 0 : port, backlog, ip);
            }
            if (options != null) {
                for (@Nonnull NetOption<?> option : options) {
                    option.applyTo(serverSocket);
                }
            }
            return new BlockingTcpNetServer(serverSocket, listener, bufSize, acceptExecutor, workExecutor);
        }

        private @Nonnull TcpNetServer buildNonBlocking(
            @Nonnull Listener listener,
            @Nonnull Executor acceptExecutor,
            @Nonnull Executor workExecutor
        ) throws Exception {
            ServerSocket serverSocket;
            if (ip == null) {
                serverSocket = new ServerSocket(port == null ? 0 : port, backlog);
            } else {
                serverSocket = new ServerSocket(port == null ? 0 : port, backlog, ip);
            }
            if (options != null) {
                for (@Nonnull NetOption<?> option : options) {
                    option.applyTo(serverSocket);
                }
            }
            return new BlockingTcpNetServer(serverSocket, listener, bufSize, acceptExecutor, workExecutor);
        }
    }
}
