package xyz.sunqian.common.net.tcp;

import xyz.sunqian.annotations.Nonnull;
import xyz.sunqian.annotations.Nullable;
import xyz.sunqian.common.net.NetClient;

import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

/**
 * This interface represents a TCP/IP network client.
 *
 * @author sunqian
 */
public interface TcpNetClient extends NetClient<InetSocketAddress> {

    /**
     * Returns the port number to which this client connects, may be {@code -1} if the client does not connect yet.
     *
     * @return the port number to which this client connects, may be {@code -1} if the client does not connect yet
     */
    default int getRemotePort() {
        InetSocketAddress address = remoteAddress();
        return address != null ? address.getPort() : -1;
    }

    /**
     * Returns the IP this client connects to, may be {@code null} if the client does not connect yet.
     *
     * @return the IP this client connects to, may be {@code null} if the client does not connect yet
     */
    default @Nullable InetAddress getRemoteIp() {
        InetSocketAddress address = remoteAddress();
        return address != null ? address.getAddress() : null;
    }

    /**
     * Returns the port number to which this server is bound, may be {@code -1} if the server is not bound yet.
     *
     * @return the port number to which this server is bound, may be {@code -1} if the server is not bound yet
     */
    default int getLocalPort() {
        InetSocketAddress address = localAddress();
        return address != null ? address.getPort() : -1;
    }

    /**
     * Returns the local IP this server is bound to, may be {@code null} if the server is not bound yet.
     *
     * @return the local IP this server is bound to, may be {@code null} if the server is not bound yet
     */
    default @Nullable InetAddress getLocalIp() {
        InetSocketAddress address = localAddress();
        return address != null ? address.getAddress() : null;
    }

    /**
     * Event listener for {@link TcpNetClient}.
     * <p>
     * Except for the {@link #onMessage(TcpNetEndpoint, ByteBuffer)}, which must be implemented, all other methods have
     * default empty methods.
     *
     * @author sunqian
     */
    interface Listener {

        /**
         * This method is invoked after the client has been started. It is the first invocation among all the listening
         * methods, and will only be invoked once.
         *
         * @throws Exception if any error occurs
         */
        default void onOpen() throws Exception {
        }

        /**
         * This method is invoked after the underlying client has been closed. It is the last invocation among all the
         * listening methods, and will only be invoked once.
         *
         * @throws Exception if any error occurs
         */
        default void onClose() throws Exception {
        }

        /**
         * This method is invoked when the connection is successfully established, and only invoked once.
         *
         * @param endpoint the remote endpoint of the connection
         * @throws Exception if any error occurs
         */
        default void onConnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
        }

        /**
         * This method is invoked when the client is failed to connect to the server, and only invoked once.
         *
         * @param endpoint the remote endpoint of the connection
         * @param cause    the cause of the failure
         * @throws Exception if any error occurs
         */
        default void onConnectionFailed(@Nonnull TcpNetEndpoint endpoint, @Nonnull Throwable cause) throws Exception {
        }

        /**
         * This method is invoked when the client disconnects, and only invoked once.
         *
         * @param endpoint the remote endpoint of the connection
         * @throws Exception if any error occurs
         */
        default void onDisconnection(@Nonnull TcpNetEndpoint endpoint) throws Exception {
        }

        /**
         * This method is invoked when an exception occurs. The exception may be an unhandled exception from other
         * listener methods, or generated by the client.
         *
         * @param client    the client
         * @param endpoint  the remote endpoint, may be {@code null} if the exception is generated by the client
         * @param throwable the exception
         */
        default void onException(@Nonnull TcpNetClient client, @Nullable TcpNetEndpoint endpoint, Throwable throwable) {
        }

        /**
         * This method is invoked when a message is received.
         *
         * @param endpoint the remote endpoint
         * @param msg      the message
         * @throws Exception if any error occurs
         */
        void onMessage(@Nonnull TcpNetEndpoint endpoint, @Nonnull ByteBuffer msg) throws Exception;
    }
}
