package space.sunqian.fs.utils.sql.annotation;

import space.sunqian.fs.utils.sql.SqlNameMapper;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation is used to map a column in the database to a property in the Java class:
 * <pre>{@code
 * @SqlColumn("CREATED_BY")
 * private String createdBy;
 * }</pre>
 * It can be used on getters, setters, and backing fields, and it takes effect according to this priority.
 *
 * @author sunqian
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({
    ElementType.METHOD,
    ElementType.FIELD,
})
public @interface SqlColumn {

    /**
     * The column name to be mapped, default is empty, which means using the default policy to map. The actual policy
     * depends on the actual executor, the system default policy is as in {@link SqlNameMapper#defaultMapper()}.
     *
     * @return the column name to be mapped
     */
    String value() default "";

    // /**
    //  * Tells whether this column is auto-generated by the database or not. The default is {@code false}.
    //  *
    //  * @return {@code true} if this column is auto-generated, {@code false} otherwise
    //  */
    // boolean autoGenerated() default false;

    /**
     * Tells whether this column is the primary key of the table or not. The default is {@code false}.
     *
     * @return {@code true} if this column is the primary key, {@code false} otherwise
     */
    boolean primary() default false;
}
