package space.sunqian.fs.utils.sql;

import space.sunqian.annotation.Nonnull;
import space.sunqian.fs.Fs;

import java.util.Collections;
import java.util.List;

/**
 * This class represents the result of a SQL insert operation.
 *
 * @param <I> the type of the auto-generated key at the first column of the result set
 * @author sunqian
 */
@SuppressWarnings("ClassCanBeRecord")
public class SqlInsertResult<I> {

    /**
     * Returns an empty {@code SqlInsertResult} whose inserted rows is 0 and auto-generated keys is an empty list.
     *
     * @param <I> the type of the auto-generated key at the first column of the result set
     * @return an empty {@code SqlInsertResult}
     */
    public static <I> @Nonnull SqlInsertResult<I> empty() {
        return Fs.as(EMPTY);
    }

    private static final @Nonnull SqlInsertResult<?> EMPTY =
        new SqlInsertResult<>(0, Collections.emptyList());
    private static final @Nonnull SqlInsertResult<?> ONE =
        new SqlInsertResult<>(1, Collections.singletonList(null));

    private final int insertedRows;
    private final @Nonnull List<I> autoGeneratedKeys;

    /**
     * Constructs a new {@code SqlInsertResult} with the given inserted rows and auto-generated keys.
     *
     * @param insertedRows      the number of rows inserted
     * @param autoGeneratedKeys the list of auto-generated keys
     */
    public SqlInsertResult(int insertedRows, @Nonnull List<I> autoGeneratedKeys) {
        this.insertedRows = insertedRows;
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    /**
     * Returns the number of rows inserted.
     *
     * @return the number of rows inserted
     */
    public int insertedRows() {
        return insertedRows;
    }

    /**
     * Returns the list of auto-generated keys which come from the first column of the result set. If no auto-generated
     * key is available, returns an empty list.
     *
     * @return the list of auto-generated keys which come from the first column of the result set
     */
    public @Nonnull List<I> autoGeneratedKeys() {
        return autoGeneratedKeys;
    }
}
