package space.sunqian.fs.utils.sql;

import space.sunqian.annotation.Nonnull;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

public interface SqlResult {

    /**
     * Returns an empty {@link OfInsert} whose inserted rows is 0 and auto-generated key list is empty.
     *
     * @param <I> the type of the auto-generated key at the first column of the result set
     * @return an empty {@link OfInsert}
     */
    static <I> @Nonnull OfInsert<I> emptyInsert() {
        return SqlResultBack.OfInsertImpl.empty();
    }

    /**
     * Returns a new {@link OfInsert} with the given inserted rows and auto-generated keys.
     *
     * @param insertedRows      the number of rows inserted
     * @param autoGeneratedKeys the list of auto-generated keys
     */
    static <I> @Nonnull OfInsert<I> ofInsert(int insertedRows, @Nonnull List<I> autoGeneratedKeys) {
        return new SqlResultBack.OfInsertImpl<>(insertedRows, autoGeneratedKeys);
    }

    /**
     * Returns a new {@link OfUpdate} with the given updated rows.
     *
     * @param updatedRows the number of rows updated
     * @return a new {@link OfUpdate}
     */
    static @Nonnull OfUpdate ofUpdate(int updatedRows) {
        return new SqlResultBack.OfUpdateImpl(updatedRows);
    }

    /**
     * Returns a new {@link OfDelete} with the given deleted rows.
     *
     * @param deletedRows the number of rows deleted
     * @return a new {@link OfDelete}
     */
    static @Nonnull OfDelete ofDelete(int deletedRows) {
        return new SqlResultBack.OfDeleteImpl(deletedRows);
    }

    /**
     * Returns the {@link SqlCaller} that created this result.
     *
     * @return the {@link SqlCaller} that created this result
     */
    SqlCaller sqlCaller();

    /**
     * Returns the statement bound to this result.
     *
     * @return the statement bound to this result
     */
    @Nonnull
    Statement statement();

    /**
     * Returns the statement bound to this result as a prepared statement if it is a prepared statement, otherwise a
     * {@link SqlRuntimeException} is thrown.
     *
     * @return the statement bound to this result as a prepared statement
     */
    default @Nonnull PreparedStatement preparedStatement() throws SqlRuntimeException {
        Statement statement = statement();
        if (statement instanceof PreparedStatement) {
            return (PreparedStatement) statement;
        }
        throw new SqlRuntimeException("The statement is not a prepared statement.");
    }

    /**
     * Represents the result of a SQL insert operation.
     *
     * @param <I> the type of the auto-generated key at the first column of the result set
     * @author sunqian
     */
    interface OfInsert<I> {

        /**
         * Returns the number of rows inserted.
         *
         * @return the number of rows inserted
         */
        int insertedRows();

        /**
         * Returns the list of auto-generated keys which come from the first column of the result set. If no
         * auto-generated key is available, returns an empty list.
         *
         * @return the list of auto-generated keys which come from the first column of the result set
         */
        @Nonnull
        List<I> autoGeneratedKeys();
    }

    /**
     * Represents the result of a SQL update operation.
     *
     * @author sunqian
     */
    interface OfUpdate {

        /**
         * Returns the number of rows updated.
         *
         * @return the number of rows updated
         */
        int updatedRows();
    }

    /**
     * Represents the result of a SQL delete operation.
     *
     * @author sunqian
     */
    interface OfDelete {

        /**
         * Returns the number of rows deleted.
         *
         * @return the number of rows deleted
         */
        int deletedRows();
    }
}
