package space.sunqian.fs.utils.sql;

import space.sunqian.annotation.Nonnull;
import space.sunqian.fs.Fs;

import java.util.Collections;
import java.util.List;

final class SqlResultBack {

    static final class OfInsertImpl<I> implements SqlResult.OfInsert<I> {

        static <I> @Nonnull SqlResult.OfInsert<I> empty() {
            return Fs.as(EMPTY);
        }

        private static final @Nonnull SqlResult.OfInsert<?> EMPTY =
            new OfInsertImpl<>(0, Collections.emptyList());
        private static final @Nonnull SqlResult.OfInsert<?> ONE =
            new OfInsertImpl<>(1, Collections.singletonList(null));

        private final int insertedRows;
        private final @Nonnull List<I> autoGeneratedKeys;

        OfInsertImpl(int insertedRows, @Nonnull List<I> autoGeneratedKeys) {
            this.insertedRows = insertedRows;
            this.autoGeneratedKeys = autoGeneratedKeys;
        }

        public int insertedRows() {
            return insertedRows;
        }

        public @Nonnull List<I> autoGeneratedKeys() {
            return autoGeneratedKeys;
        }
    }

    static final class OfUpdateImpl implements SqlResult.OfUpdate {

        private final int updatedRows;

        OfUpdateImpl(int updatedRows) {
            this.updatedRows = updatedRows;
        }

        public int updatedRows() {
            return updatedRows;
        }
    }

    static final class OfDeleteImpl implements SqlResult.OfDelete {

        private final int deletedRows;

        OfDeleteImpl(int deletedRows) {
            this.deletedRows = deletedRows;
        }

        public int deletedRows() {
            return deletedRows;
        }
    }
}
