package tests.core.utils.sql;

import internal.annotations.J17Only;
import lombok.Data;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import space.sunqian.fs.Fs;
import space.sunqian.fs.object.convert.ObjectConverter;
import space.sunqian.fs.object.meta.ObjectMeta;
import space.sunqian.fs.object.meta.ObjectMetaIntrospector;
import space.sunqian.fs.reflect.TypeRef;
import space.sunqian.fs.utils.sql.SqlCallableParameter;
import space.sunqian.fs.utils.sql.SqlInsertResult;
import space.sunqian.fs.utils.sql.SqlKit;
import space.sunqian.fs.utils.sql.SqlNameMapper;
import space.sunqian.fs.utils.sql.SqlParameter;
import space.sunqian.fs.utils.sql.SqlRuntimeException;
import space.sunqian.fs.utils.sql.annotation.SqlColumn;
import space.sunqian.fs.utils.sql.annotation.SqlTable;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.JDBCType;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@J17Only
public class SqlKitTest {

    // private static final String DB_DRIVER = "org.h2.Driver";
    // private static final String DB_URL = "jdbc:h2:mem:" + SqlKitTest.class.getName();
    // private static final String DB_USER = "sa";
    // private static final String DB_PASSWORD = "";

    private static final String DB_DRIVER = "org.hsqldb.jdbc.JDBCDriver";
    private static final String DB_URL = "jdbc:hsqldb:mem:" + SqlKitTest.class.getName() + ";sql.syntax_mys=true";
    private static final String DB_USER = "SA";
    private static final String DB_PASSWORD = "";

    private static final ObjectMetaIntrospector INTROSPECTOR = ObjectMetaIntrospector.defaultIntrospector();
    private static final SqlNameMapper NAME_MAPPER = SqlNameMapper.defaultMapper();
    private static final ObjectConverter CONVERTER = ObjectConverter.defaultConverter();

    private static Connection connection;

    @BeforeEach
    public void setUpEach() throws SQLException, ClassNotFoundException {

        // init connection
        Class.forName(DB_DRIVER);
        connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);

        // create table `USER`
        // `ID` (auto increment), `USER_NAME`, `AGE`, `BIRTHDAY`
        try (Statement statement = connection.createStatement()) {
            statement.execute(
                "create table if not exists `USER` (" +
                    //"ID int primary key auto_increment, " +
                    "ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                    "USER_NAME varchar(16), " +
                    "AGE int, " +
                    "BIRTHDAY timestamp, " +
                    "USER_PASSWORD varchar(255)" +
                    ")"
            );
        }

        // create table `USER_PASSWORD`
        // USER_ID, USER_PASSWORD
        try (Statement statement = connection.createStatement()) {
            statement.execute(
                "create table if not exists `USER_PASSWORD` (" +
                    "USER_ID INTEGER, " +
                    "USER_PASSWORD varchar(256)" +
                    ")"
            );
        }

        // create procedure `test_proc`
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE PROCEDURE test_proc(" +
                "                    IN p_in1 INTEGER," +
                "                    IN p_in2 INTEGER," +
                "                    IN p_in3 INTEGER," +
                "                    OUT p_out INTEGER," +
                "                    INOUT p_inout INTEGER" +
                "                )" +
                "                MODIFIES SQL DATA" +
                "                BEGIN ATOMIC" +
                "                    SET p_out = p_in1 + p_in2 + p_in3;" +
                "                    SET p_inout = p_inout + p_inout;" +
                "                END");
        }
    }

    @AfterEach
    public void destroyEach() throws SQLException, ClassNotFoundException {
        // Drop table `USER`
        try (Statement statement = connection.createStatement()) {
            statement.execute("drop table if exists `USER`");
        }
        // Drop procedure `test_proc`
        try (Statement statement = connection.createStatement()) {
            statement.execute("drop procedure if exists test_proc;");
        }
        // Close connection
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    public void testSetParameters() throws Exception {
        {
            // for SqlParameter
            Date now = new Date();
            String insertSql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<?> insertParams = Fs.list(
                "Alice",
                null,
                now
            );
            PreparedStatement insertStatement = connection.prepareStatement(insertSql);
            SqlKit.setParameters(insertStatement, insertParams);
            int inserted = insertStatement.executeUpdate();
            assertEquals(1, inserted);
            insertStatement.close();
            Statement queryStatement = connection.createStatement();
            ResultSet queryResult = queryStatement.executeQuery("select * from `USER`;");
            assertTrue(queryResult.next());
            assertEquals("Alice", queryResult.getString("USER_NAME"));
            assertEquals(0, queryResult.getInt("AGE"));
            assertNull(queryResult.getObject("AGE"));
            assertEquals(
                now.toInstant(),
                queryResult.getTimestamp("BIRTHDAY").toInstant()
            );
            queryStatement.close();
            queryResult.close();
            // clear data
            clearData();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(insertStatement, insertParams)
            );
        }
        {
            // for SqlCallableParameter
            Date now = new Date();
            String insertSql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<?> insertParams = Fs.list(
                "Alice",
                null,
                now
            );
            // perform as prepared statement
            CallableStatement insertStatement = connection.prepareCall(insertSql);
            SqlKit.setParameters(insertStatement, insertParams);
            int inserted = insertStatement.executeUpdate();
            assertEquals(1, inserted);
            insertStatement.close();
            // perform as callable statement
            String procSql = "{call test_proc(?, ?, ?, ?, ?)}";
            CallableStatement procStatement = connection.prepareCall(procSql);
            List<?> procParams = Fs.list(
                SqlCallableParameter.of(1, Types.INTEGER, SqlCallableParameter.Mode.IN),
                SqlParameter.of(2, Types.INTEGER),
                3,
                SqlCallableParameter.of(4, Types.INTEGER, SqlCallableParameter.Mode.OUT),
                SqlCallableParameter.of(5, Types.INTEGER, SqlCallableParameter.Mode.IN_OUT)
            );
            SqlKit.setParameters(procStatement, procParams);
            procStatement.execute();
            assertEquals(6, procStatement.getInt(4));
            assertEquals(10, procStatement.getInt(5));
            procStatement.close();
            // clear data
            clearData();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(insertStatement, insertParams)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(procStatement, procParams)
            );
        }
        {
            // for batches
            Date now = new Date();
            String insertSql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<List<?>> insertParams = Fs.list(
                Fs.list(
                    SqlParameter.of("Alice", JDBCType.VARCHAR),
                    SqlParameter.of(null, Types.INTEGER),
                    now
                ),
                Fs.list(
                    "Bob",
                    SqlParameter.of(18, Types.INTEGER),
                    null
                )
            );
            PreparedStatement insertStatement = connection.prepareStatement(insertSql);
            SqlKit.setParameterBatches(insertStatement, insertParams);
            int inserted = insertStatement.executeBatch().length;
            assertEquals(2, inserted);
            insertStatement.close();
            Statement queryStatement = connection.createStatement();
            ResultSet queryResult = queryStatement.executeQuery("select * from `USER` order by ID asc;");
            assertTrue(queryResult.next());
            assertEquals("Alice", queryResult.getString("USER_NAME"));
            assertEquals(0, queryResult.getInt("AGE"));
            assertNull(queryResult.getObject("AGE"));
            assertEquals(
                now.toInstant(),
                queryResult.getTimestamp("BIRTHDAY").toInstant()
            );
            assertTrue(queryResult.next());
            assertEquals("Bob", queryResult.getString("USER_NAME"));
            assertEquals(18, queryResult.getInt("AGE"));
            assertNull(queryResult.getObject("BIRTHDAY"));
            assertNull(queryResult.getTimestamp("BIRTHDAY"));
            queryStatement.close();
            queryResult.close();
            // clear data
            clearData();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameterBatches(insertStatement, insertParams)
            );
        }
    }

    @Test
    public void testReadRow() throws Exception {
        Date now = new Date();
        {
            // init data
            String sql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<List<?>> params = Fs.list(
                Fs.list("Alice", 25, now),
                Fs.list("Bob", 18, now),
                Fs.list("Charlie", 22, now)
            );
            PreparedStatement statement = connection.prepareStatement(sql);
            SqlKit.setParameterBatches(statement, params);
            int inserted = statement.executeBatch().length;
            assertEquals(3, inserted);
            statement.close();
        }
        {
            // test next row
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            User alice = SqlKit.nextRow(
                resultSet,
                User.class,
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals("Alice", alice.getUserName());
            assertEquals(25, alice.getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), alice.getBirthday());
            Map<String, Object> userMap = SqlKit.nextRow(
                resultSet,
                NAME_MAPPER.toPropertyNameMapper()
            );
            assertEquals("Bob", userMap.get("userName"));
            assertEquals(18, userMap.get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) userMap.get("birthday")).toInstant()
            );
            // test next row with type ref
            User charlie = SqlKit.nextRow(
                resultSet,
                new TypeRef<User>() {},
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals("Charlie", charlie.getUserName());
            assertEquals(22, charlie.getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), charlie.getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.nextRow(
                    resultSet,
                    User.class,
                    INTROSPECTOR,
                    NAME_MAPPER.toPropertyNameMapper(),
                    CONVERTER
                )
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.nextRow(
                    resultSet,
                    NAME_MAPPER.toPropertyNameMapper()
                )
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.nextRow(
                    resultSet,
                    new TypeRef<User>() {},
                    INTROSPECTOR,
                    NAME_MAPPER.toPropertyNameMapper(),
                    CONVERTER
                )
            );
        }
        {
            // test read rows
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> users = SqlKit.readRows(
                resultSet,
                User.class,
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals("Alice", users.get(0).getUserName());
            assertEquals(25, users.get(0).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(0).getBirthday());
            assertEquals("Bob", users.get(1).getUserName());
            assertEquals(18, users.get(1).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(1).getBirthday());
            assertEquals("Charlie", users.get(2).getUserName());
            assertEquals(22, users.get(2).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(2).getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.readRows(
                    resultSet,
                    User.class,
                    INTROSPECTOR,
                    NAME_MAPPER.toPropertyNameMapper(),
                    CONVERTER
                )
            );
        }
        {
            // test read rows with type ref
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> users = SqlKit.readRows(
                resultSet,
                new TypeRef<User>() {},
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals("Alice", users.get(0).getUserName());
            assertEquals(25, users.get(0).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(0).getBirthday());
            assertEquals("Bob", users.get(1).getUserName());
            assertEquals(18, users.get(1).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(1).getBirthday());
            assertEquals("Charlie", users.get(2).getUserName());
            assertEquals(22, users.get(2).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(2).getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.readRows(
                    resultSet,
                    new TypeRef<User>() {},
                    INTROSPECTOR,
                    NAME_MAPPER.toPropertyNameMapper(),
                    CONVERTER
                )
            );
        }
        {
            // test read rows to a list map
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<Map<String, Object>> users = SqlKit.readRows(
                resultSet,
                NAME_MAPPER.toPropertyNameMapper()
            );
            assertEquals("Alice", users.get(0).get("userName"));
            assertEquals(25, users.get(0).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(0).get("birthday")).toInstant()
            );
            assertEquals("Bob", users.get(1).get("userName"));
            assertEquals(18, users.get(1).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(1).get("birthday")).toInstant()
            );
            assertEquals("Charlie", users.get(2).get("userName"));
            assertEquals(22, users.get(2).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(2).get("birthday")).toInstant()
            );
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.readRows(
                    resultSet,
                    NAME_MAPPER.toPropertyNameMapper()
                )
            );
        }
        {
            // clear data
            clearData();
        }
    }

    @Test
    public void testInsertRow() throws Exception {
        ZonedDateTime birthday = ZonedDateTime.ofInstant(new Date().toInstant(), ZoneId.systemDefault());
        {
            // insert one row
            User user = new User();
            user.setUserName("Alice");
            user.setAge(25);
            user.setBirthday(birthday);
            user.setOther1("other1");
            user.setOther2("other2");
            SqlInsertResult<Long> userResult =
                SqlKit.insertRow(connection, user, Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER);
            assertEquals(1, userResult.insertedRows());
            assertEquals(1L, userResult.autoGeneratedKeys().get(0));
            // test no generated key
            UserPassword userPassword = new UserPassword();
            userPassword.setUserId(userResult.autoGeneratedKeys().get(0));
            userPassword.setUserPassword("123456");
            SqlInsertResult<Long> passwordResult =
                SqlKit.insertRow(connection, userPassword, Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER);
            assertEquals(1, passwordResult.insertedRows());
            assertTrue(passwordResult.autoGeneratedKeys().isEmpty());
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRow(connection, new NoTable(), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRow(connection, new NoColumn(), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRow(connection, new SomeTable(), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
        }
        {
            // insert rows
            List<User> users = new ArrayList<>();
            User bob = new User();
            bob.setUserName("Bob");
            bob.setAge(18);
            bob.setBirthday(birthday);
            users.add(bob);
            User charlie = new User();
            charlie.setUserName("Charlie");
            charlie.setAge(22);
            charlie.setBirthday(birthday);
            users.add(charlie);
            SqlInsertResult<Long> userResult =
                SqlKit.insertRows(connection, users, Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER);
            assertEquals(2, userResult.insertedRows());
            assertEquals(2L, userResult.autoGeneratedKeys().get(0));
            assertEquals(3L, userResult.autoGeneratedKeys().get(1));
            // test no generated key
            UserPassword bobPassword = new UserPassword();
            bobPassword.setUserId(userResult.autoGeneratedKeys().get(0));
            bobPassword.setUserPassword("123456");
            UserPassword charliePassword = new UserPassword();
            charliePassword.setUserId(userResult.autoGeneratedKeys().get(1));
            charliePassword.setUserPassword("123456");
            SqlInsertResult<Long> passwordResult = SqlKit.insertRows(
                connection, Fs.list(bobPassword, charliePassword), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER
            );
            assertEquals(2, passwordResult.insertedRows());
            assertTrue(passwordResult.autoGeneratedKeys().isEmpty());
            // exception
            assertSame(
                SqlInsertResult.empty(),
                SqlKit.insertRows(connection, Fs.list(), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRows(connection, Fs.list(new NoTable()), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRows(connection, Fs.list(new NoColumn()), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRows(connection, Fs.list(new NoColumn()), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.insertRows(connection, Fs.list(new SomeTable()), Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER)
            );
        }
        {
            // check inserted rows
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> insertedUsers = SqlKit.readRows(
                resultSet,
                new TypeRef<User>() {},
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals(3, insertedUsers.size());
            assertEquals(1L, insertedUsers.get(0).getId());
            assertEquals("Alice", insertedUsers.get(0).getUserName());
            assertEquals(25, insertedUsers.get(0).getAge());
            assertEquals(birthday, insertedUsers.get(0).getBirthday());
            assertEquals(2L, insertedUsers.get(1).getId());
            assertEquals("Bob", insertedUsers.get(1).getUserName());
            assertEquals(18, insertedUsers.get(1).getAge());
            assertEquals(birthday, insertedUsers.get(1).getBirthday());
            assertEquals(3L, insertedUsers.get(2).getId());
            assertEquals("Charlie", insertedUsers.get(2).getUserName());
            assertEquals(22, insertedUsers.get(2).getAge());
            assertEquals(birthday, insertedUsers.get(2).getBirthday());
            statement.close();
            resultSet.close();
        }
        {
            // clear data
            clearData();
        }
    }

    @Test
    public void testUpdateByPrimaryKey() throws Exception {
        ZonedDateTime birthday = ZonedDateTime.ofInstant(new Date().toInstant(), ZoneId.systemDefault());
        {
            // insert rows
            List<User> users = new ArrayList<>();
            User alice = new User();
            alice.setUserName("Alice");
            alice.setAge(25);
            alice.setBirthday(birthday);
            users.add(alice);
            User bob = new User();
            bob.setUserName("Bob");
            bob.setAge(18);
            bob.setBirthday(birthday);
            users.add(bob);
            User charlie = new User();
            charlie.setUserName("Charlie");
            charlie.setAge(22);
            charlie.setBirthday(birthday);
            users.add(charlie);
            SqlInsertResult<Long> userResult =
                SqlKit.insertRows(connection, users, Long.class, INTROSPECTOR, NAME_MAPPER, CONVERTER);
            UserPassword bobPassword = new UserPassword();
            bobPassword.setUserId(userResult.autoGeneratedKeys().get(0));
            bobPassword.setUserPassword("123456");
            UserPassword charliePassword = new UserPassword();
            charliePassword.setUserId(userResult.autoGeneratedKeys().get(1));
            charliePassword.setUserPassword("123456");
        }
        {
            // update rows
            User updateAlice = new User();
            updateAlice.setId(1L);
            updateAlice.setUserName("Alice2");
            updateAlice.setAge(66);
            updateAlice.setBirthday(null);
            assertEquals(1, SqlKit.updateByPrimaryKey(connection, updateAlice, INTROSPECTOR, NAME_MAPPER));
            User updateAll = new User();
            updateAll.setAge(99);
            updateAll.setUserName(null);
            updateAll.setBirthday(null);
            assertEquals(
                2,
                SqlKit.updateByPrimaryKeys(connection, updateAll, Fs.list(2L, 3L), INTROSPECTOR, NAME_MAPPER)
            );
        }
        {
            // check updated rows
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> insertedUsers = SqlKit.readRows(
                resultSet,
                new TypeRef<User>() {},
                INTROSPECTOR,
                NAME_MAPPER.toPropertyNameMapper(),
                CONVERTER
            );
            assertEquals(3, insertedUsers.size());
            assertEquals(1L, insertedUsers.get(0).getId());
            assertEquals("Alice2", insertedUsers.get(0).getUserName());
            assertEquals(66, insertedUsers.get(0).getAge());
            assertEquals(birthday, insertedUsers.get(0).getBirthday());
            assertEquals(2L, insertedUsers.get(1).getId());
            assertEquals("Bob", insertedUsers.get(1).getUserName());
            assertEquals(99, insertedUsers.get(1).getAge());
            assertEquals(birthday, insertedUsers.get(1).getBirthday());
            assertEquals(3L, insertedUsers.get(2).getId());
            assertEquals("Charlie", insertedUsers.get(2).getUserName());
            assertEquals(99, insertedUsers.get(2).getAge());
            assertEquals(birthday, insertedUsers.get(2).getBirthday());
            statement.close();
            resultSet.close();
        }
        {
            // exception
            User updateAlice = new User();
            updateAlice.setId(null);
            updateAlice.setUserName("Alice3");
            updateAlice.setAge(77);
            updateAlice.setBirthday(null);
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, updateAlice, INTROSPECTOR, NAME_MAPPER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKeys(connection, updateAlice, Fs.list(), INTROSPECTOR, NAME_MAPPER)
            );
            updateAlice.setId(1L);
            updateAlice.setUserName("123456789012345678901234567890");// overflow
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, updateAlice, INTROSPECTOR, NAME_MAPPER)
            );
            NoUpdatable noUpdatable = new NoUpdatable();
            noUpdatable.setId(1L);
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, noUpdatable, INTROSPECTOR, NAME_MAPPER)
            );
            MultiPrimary multiPrimary = new MultiPrimary();
            multiPrimary.setId(1L);
            multiPrimary.setUserName("Alice4");
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, multiPrimary, INTROSPECTOR, NAME_MAPPER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, new UserPassword(), INTROSPECTOR, NAME_MAPPER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, new NoTable(), INTROSPECTOR, NAME_MAPPER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, new NoColumn(), INTROSPECTOR, NAME_MAPPER)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.updateByPrimaryKey(connection, new SomeTable(), INTROSPECTOR, NAME_MAPPER)
            );
        }
        {
            // clear data
            clearData();
        }
    }

    private void clearData() throws Exception {
        try (Statement clearStatement = connection.createStatement()) {
            clearStatement.execute("delete from `USER`;");
            clearStatement.execute("delete from `USER_PASSWORD`;");
        }
    }

    @Test
    public void testNameMapping() throws Exception {
        ObjectMeta tableMeta = ObjectMeta.of(SomeTable.class);
        ObjectMeta tableXMeta = ObjectMeta.of(SomeTableX.class);
        {
            // test column name mapping
            assertEquals("USER_NAME", SqlKit.toColumnName(
                    "userName",
                    tableMeta.getProperty("userName").annotations().annotation(SqlColumn.class),
                    NAME_MAPPER
                )
            );
            assertEquals("USER_AGE", SqlKit.toColumnName(
                    "age",
                    tableMeta.getProperty("age").annotations().annotation(SqlColumn.class),
                    NAME_MAPPER
                )
            );
        }
        {
            // test table name mapping
            assertEquals("SOME_TABLE", SqlKit.toTableName(
                    SomeTable.class,
                    tableMeta.annotations().annotation(SqlTable.class),
                    NAME_MAPPER
                )
            );
            assertEquals("SOME_TABLE_XXX", SqlKit.toTableName(
                    SomeTableX.class,
                    tableXMeta.annotations().annotation(SqlTable.class),
                    NAME_MAPPER
                )
            );
            assertEquals("SOME_TABLE", SqlKit.toTableName(
                    SomeTable.class.getName(),
                    tableMeta.annotations().annotation(SqlTable.class),
                    NAME_MAPPER
                )
            );
            assertEquals("SOME_TABLE_XXX", SqlKit.toTableName(
                    SomeTableX.class.getName(),
                    tableXMeta.annotations().annotation(SqlTable.class),
                    NAME_MAPPER
                )
            );
        }
    }

    @Data
    @SqlTable
    public static class User {
        @SqlColumn(autoGenerated = true, primary = true)
        private Long id;
        @SqlColumn
        private String userName;
        @SqlColumn
        private int age;
        @SqlColumn
        private ZonedDateTime birthday;

        // other fields
        private String other1;
        private String other2;
    }

    @Data
    @SqlTable
    public static class UserPassword {
        @SqlColumn
        private Long userId;
        @SqlColumn
        private String userPassword;
    }

    @Data
    @SqlTable
    public static class SomeTable {
        @SqlColumn
        private Long id;
        @SqlColumn
        private String userName;
        @SqlColumn("USER_AGE")
        private int age;
        @SqlColumn
        private ZonedDateTime birthday;
    }

    @Data
    @SqlTable("SOME_TABLE_XXX")
    public static class SomeTableX {
    }

    @Data
    public static class NoTable {
        @SqlColumn
        private Long id;
        @SqlColumn
        private String userName;
        @SqlColumn("USER_AGE")
        private int age;
        @SqlColumn
        private ZonedDateTime birthday;
    }

    @Data
    @SqlTable
    public static class NoColumn {
        private Long id;
        private String userName;
        private int age;
        private ZonedDateTime birthday;
    }

    @Data
    @SqlTable
    public static class NoUpdatable {
        @SqlColumn(primary = true)
        private Long id;
        @SqlColumn
        private String userName;
    }

    @Data
    @SqlTable
    public static class MultiPrimary {
        @SqlColumn(primary = true)
        private Long id;
        @SqlColumn(primary = true)
        private String userName;
    }
}