package tests.core.utils.sql;

import internal.annotations.J17Only;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import space.sunqian.fs.Fs;
import space.sunqian.fs.object.convert.ObjectConverter;
import space.sunqian.fs.object.meta.ObjectMeta;
import space.sunqian.fs.object.meta.ObjectMetaIntrospector;
import space.sunqian.fs.reflect.TypeRef;
import space.sunqian.fs.utils.sql.SqlCallableParameter;
import space.sunqian.fs.utils.sql.SqlKit;
import space.sunqian.fs.utils.sql.SqlNameMapper;
import space.sunqian.fs.utils.sql.SqlParameter;
import space.sunqian.fs.utils.sql.SqlRuntimeException;
import space.sunqian.fs.utils.sql.annotation.SqlColumn;
import space.sunqian.fs.utils.sql.annotation.SqlTable;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.JDBCType;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@J17Only
public class SqlKitTest {

    // private static final String DB_DRIVER = "org.h2.Driver";
    // private static final String DB_URL = "jdbc:h2:mem:" + SqlKitTest.class.getName();
    // private static final String DB_USER = "sa";
    // private static final String DB_PASSWORD = "";

    private static final String DB_DRIVER = "org.hsqldb.jdbc.JDBCDriver";
    private static final String DB_URL = "jdbc:hsqldb:mem:" + SqlKitTest.class.getName() + ";sql.syntax_mys=true";
    private static final String DB_USER = "SA";
    private static final String DB_PASSWORD = "";

    private static Connection h2Connection;

    @BeforeEach
    public void setUpEach() throws SQLException, ClassNotFoundException {
        Class.forName(DB_DRIVER);
        h2Connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);

        // create table `USER`
        // `ID` (auto increment), `USER_NAME`, `AGE`, `BIRTHDAY`
        PreparedStatement preparedStatement = h2Connection.prepareStatement(
            "create table if not exists `USER` (" +
                //"ID int primary key auto_increment, " +
                "ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "USER_NAME varchar(255), " +
                "AGE int, " +
                "BIRTHDAY timestamp, " +
                "USER_PASSWORD varchar(255)" +
                ")"
        );
        preparedStatement.execute();

        // create procedure `test_proc`
        try (Statement stmt = h2Connection.createStatement()) {
            stmt.execute("CREATE PROCEDURE test_proc(" +
                "                    IN p_in1 INTEGER," +
                "                    IN p_in2 INTEGER," +
                "                    IN p_in3 INTEGER," +
                "                    OUT p_out INTEGER," +
                "                    INOUT p_inout INTEGER" +
                "                )" +
                "                MODIFIES SQL DATA" +
                "                BEGIN ATOMIC" +
                "                    SET p_out = p_in1 + p_in2 + p_in3;" +
                "                    SET p_inout = p_inout + p_inout;" +
                "                END");
        }
    }

    @AfterEach
    public void destroyEach() throws SQLException, ClassNotFoundException {
        // Clean up: drop test table `USER`
        PreparedStatement preparedStatement = h2Connection.prepareStatement(
            "drop table if exists `USER`"
        );
        preparedStatement.execute();
        // create procedure `test_proc`
        try (Statement stmt = h2Connection.createStatement()) {
            stmt.execute("drop procedure if exists test_proc;");
        }

        if (h2Connection != null && !h2Connection.isClosed()) {
            h2Connection.close();
        }
    }

    @Test
    public void testSetParameters() throws Exception {
        {
            // setParameters
            Date now = new Date();
            String sql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<?> params = Fs.list(
                "Alice",
                null,
                now
            );
            PreparedStatement ps = h2Connection.prepareStatement(sql);
            SqlKit.setParameters(ps, params);
            int inserted = ps.executeUpdate();
            assertEquals(1, inserted);
            ps.close();
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER`;");
            assertTrue(resultSet.next());
            assertEquals("Alice", resultSet.getString("USER_NAME"));
            assertEquals(0, resultSet.getInt("AGE"));
            assertNull(resultSet.getObject("AGE"));
            assertEquals(
                now.toInstant(),
                resultSet.getTimestamp("BIRTHDAY").toInstant()
            );
            statement.close();
            resultSet.close();
            // clear table
            Statement clear = h2Connection.createStatement();
            clear.execute("delete from `USER`;");
            clear.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(ps, params)
            );
        }
        {
            // setParameters for callable
            Date now = new Date();
            String sql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<?> params = Fs.list(
                "Alice",
                null,
                now
            );
            // perform as prepared statement
            CallableStatement cs = h2Connection.prepareCall(sql);
            SqlKit.setParameters(cs, params);
            int inserted = cs.executeUpdate();
            assertEquals(1, inserted);
            cs.close();
            // perform as callable statement
            CallableStatement csp = h2Connection.prepareCall("call test_proc(?, ?, ?, ?, ?);");
            List<?> cspParams = Fs.list(
                SqlCallableParameter.of(1, Types.INTEGER, SqlCallableParameter.Mode.IN),
                SqlParameter.of(2, Types.INTEGER),
                3,
                SqlCallableParameter.of(4, Types.INTEGER, SqlCallableParameter.Mode.OUT),
                SqlCallableParameter.of(5, Types.INTEGER, SqlCallableParameter.Mode.IN_OUT)
            );
            SqlKit.setParameters(csp, cspParams);
            csp.execute();
            assertEquals(6, csp.getInt(4));
            assertEquals(10, csp.getInt(5));
            csp.close();
            // clear table
            Statement clear = h2Connection.createStatement();
            clear.execute("delete from `USER`;");
            clear.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(cs, params)
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameters(csp, cspParams)
            );
        }
        {
            // setParameterBatches
            Date now = new Date();
            String sql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<List<?>> params = Fs.list(
                Fs.list(
                    SqlParameter.of("Alice", JDBCType.VARCHAR),
                    SqlParameter.of(null, Types.INTEGER),
                    now
                ),
                Fs.list(
                    "Bob",
                    SqlParameter.of(18, Types.INTEGER),
                    null
                )
            );
            PreparedStatement preparedStatement = h2Connection.prepareStatement(sql);
            SqlKit.setParameterBatches(preparedStatement, params);
            int inserted = preparedStatement.executeBatch().length;
            assertEquals(2, inserted);
            preparedStatement.close();
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            assertTrue(resultSet.next());
            assertEquals("Alice", resultSet.getString("USER_NAME"));
            assertEquals(0, resultSet.getInt("AGE"));
            assertNull(resultSet.getObject("AGE"));
            assertEquals(
                now.toInstant(),
                resultSet.getTimestamp("BIRTHDAY").toInstant()
            );
            assertTrue(resultSet.next());
            assertEquals("Bob", resultSet.getString("USER_NAME"));
            assertEquals(18, resultSet.getInt("AGE"));
            assertNull(resultSet.getObject("BIRTHDAY"));
            assertNull(resultSet.getTimestamp("BIRTHDAY"));
            statement.close();
            resultSet.close();
            // clear table
            Statement clear = h2Connection.createStatement();
            clear.execute("delete from `USER`;");
            clear.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.setParameterBatches(preparedStatement, params)
            );
        }
    }

    @Test
    public void testMapRow() throws Exception {
        Date now = new Date();
        {
            // init data
            String sql = "insert into `USER` (USER_NAME, AGE, BIRTHDAY) values (?, ?, ?);";
            List<List<?>> params = Fs.list(
                Fs.list("Alice", 25, now),
                Fs.list("Bob", 18, now),
                Fs.list("Charlie", 22, now)
            );
            PreparedStatement preparedStatement = h2Connection.prepareStatement(sql);
            SqlKit.setParameterBatches(preparedStatement, params);
            int inserted = preparedStatement.executeBatch().length;
            assertEquals(3, inserted);
            preparedStatement.close();
        }
        {
            // map row
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            User alice = SqlKit.mapRow(
                resultSet,
                User.class,
                ObjectMetaIntrospector.defaultIntrospector(),
                SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                ObjectConverter.defaultConverter()
            );
            assertEquals("Alice", alice.getUserName());
            assertEquals(25, alice.getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), alice.getBirthday());
            Map<String, Object> userMap = SqlKit.mapRow(
                resultSet,
                SqlNameMapper.defaultMapper().toPropertyNameMapper()
            );
            assertEquals("Bob", userMap.get("userName"));
            assertEquals(18, userMap.get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) userMap.get("birthday")).toInstant()
            );
            User charlie = SqlKit.mapRow(
                resultSet,
                new TypeRef<User>() {},
                ObjectMetaIntrospector.defaultIntrospector(),
                SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                ObjectConverter.defaultConverter()
            );
            assertEquals("Charlie", charlie.getUserName());
            assertEquals(22, charlie.getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), charlie.getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRow(
                    resultSet,
                    User.class,
                    ObjectMetaIntrospector.defaultIntrospector(),
                    SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                    ObjectConverter.defaultConverter()
                )
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRow(
                    resultSet,
                    SqlNameMapper.defaultMapper().toPropertyNameMapper()
                )
            );
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRow(
                    resultSet,
                    new TypeRef<User>() {},
                    ObjectMetaIntrospector.defaultIntrospector(),
                    SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                    ObjectConverter.defaultConverter()
                )
            );
        }
        {
            // map rows
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> users = SqlKit.mapRows(
                resultSet,
                User.class,
                ObjectMetaIntrospector.defaultIntrospector(),
                SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                ObjectConverter.defaultConverter()
            );
            assertEquals("Alice", users.get(0).getUserName());
            assertEquals(25, users.get(0).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(0).getBirthday());
            assertEquals("Bob", users.get(1).getUserName());
            assertEquals(18, users.get(1).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(1).getBirthday());
            assertEquals("Charlie", users.get(2).getUserName());
            assertEquals(22, users.get(2).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(2).getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRows(
                    resultSet,
                    User.class,
                    ObjectMetaIntrospector.defaultIntrospector(),
                    SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                    ObjectConverter.defaultConverter()
                )
            );
        }
        {
            // map rows
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<User> users = SqlKit.mapRows(
                resultSet,
                new TypeRef<User>() {},
                ObjectMetaIntrospector.defaultIntrospector(),
                SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                ObjectConverter.defaultConverter()
            );
            assertEquals("Alice", users.get(0).getUserName());
            assertEquals(25, users.get(0).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(0).getBirthday());
            assertEquals("Bob", users.get(1).getUserName());
            assertEquals(18, users.get(1).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(1).getBirthday());
            assertEquals("Charlie", users.get(2).getUserName());
            assertEquals(22, users.get(2).getAge());
            assertEquals(ZonedDateTime.ofInstant(now.toInstant(), ZoneId.systemDefault()), users.get(2).getBirthday());
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRows(
                    resultSet,
                    new TypeRef<User>() {},
                    ObjectMetaIntrospector.defaultIntrospector(),
                    SqlNameMapper.defaultMapper().toPropertyNameMapper(),
                    ObjectConverter.defaultConverter()
                )
            );
        }
        {
            // map rows
            Statement statement = h2Connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from `USER` order by ID asc;");
            List<Map<String, Object>> users = SqlKit.mapRows(
                resultSet,
                SqlNameMapper.defaultMapper().toPropertyNameMapper()
            );
            assertEquals("Alice", users.get(0).get("userName"));
            assertEquals(25, users.get(0).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(0).get("birthday")).toInstant()
            );
            assertEquals("Bob", users.get(1).get("userName"));
            assertEquals(18, users.get(1).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(1).get("birthday")).toInstant()
            );
            assertEquals("Charlie", users.get(2).get("userName"));
            assertEquals(22, users.get(2).get("age"));
            assertEquals(
                now.toInstant(),
                ((Timestamp) users.get(2).get("birthday")).toInstant()
            );
            statement.close();
            resultSet.close();
            // exception
            assertThrows(
                SqlRuntimeException.class,
                () -> SqlKit.mapRows(
                    resultSet,
                    SqlNameMapper.defaultMapper().toPropertyNameMapper()
                )
            );
        }
        {
            // clear data
            Statement clear = h2Connection.createStatement();
            clear.execute("delete from `USER`;");
            clear.close();
        }
    }

    @Test
    public void testNameMapping() throws Exception {
        {
            ObjectMeta objectMeta = ObjectMeta.of(SomeTable.class);
            assertEquals("SOME_TABLE", SqlKit.toTableName(
                    SomeTable.class,
                    objectMeta.annotations().annotation(SqlTable.class),
                    SqlNameMapper.defaultMapper().toTableNameMapper()
                )
            );
            assertEquals("USER_NAME", SqlKit.toColumnName(
                    "userName",
                    objectMeta.getProperty("userName").annotations().annotation(SqlColumn.class),
                    SqlNameMapper.defaultMapper().toColumnNameMapper()
                )
            );
            assertEquals("USER_AGE", SqlKit.toColumnName(
                    "age",
                    objectMeta.getProperty("age").annotations().annotation(SqlColumn.class),
                    SqlNameMapper.defaultMapper().toColumnNameMapper()
                )
            );
        }
        {
            ObjectMeta objectMeta = ObjectMeta.of(SomeTableX.class);
            assertEquals("SOME_TABLE_XXX", SqlKit.toTableName(
                    SomeTableX.class,
                    objectMeta.annotations().annotation(SqlTable.class),
                    SqlNameMapper.defaultMapper().toTableNameMapper()
                )
            );
        }
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    @EqualsAndHashCode
    @SqlTable
    public static class User {
        @SqlColumn
        private Long id;
        @SqlColumn
        private String userName;
        @SqlColumn
        private int age;
        @SqlColumn
        private ZonedDateTime birthday;
    }

    @Data
    @SqlTable
    public static class SomeTable {
        @SqlColumn
        private Long id;
        @SqlColumn
        private String userName;
        @SqlColumn("USER_AGE")
        private int age;
        @SqlColumn
        private ZonedDateTime birthday;
    }

    @Data
    @SqlTable("SOME_TABLE_XXX")
    public static class SomeTableX {
    }
}