package tests.core.utils.sql;

import org.junit.jupiter.api.Test;
import space.sunqian.fs.Fs;
import space.sunqian.fs.utils.sql.SqlResult;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;

public class SqlResultTest {

    @Test
    public void testResultOf() {
        // OfInsert
        assertSame(SqlResult.emptyInsert(), SqlResult.emptyInsert());
        SqlResult.OfInsert<Integer> ofInsert = SqlResult.ofInsert(5, Fs.list(1, 3, 5, 7, 9));
        assertEquals(5, ofInsert.insertedRows());
        assertEquals(Fs.list(1, 3, 5, 7, 9), ofInsert.autoGeneratedKeys());
        // OfUpdate
        SqlResult.OfUpdate ofUpdate = SqlResult.ofUpdate(3);
        assertEquals(3, ofUpdate.updatedRows());
        // OfDelete
        SqlResult.OfDelete ofDelete = SqlResult.ofDelete(2);
        assertEquals(2, ofDelete.deletedRows());
    }
}