= image:fs.svg[] Manual of _fs_
:toc:
:toclevels: 3
:last-update-label!:
孙谦 <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/fredsuvn

== Overview

_fs_ is a lightweight, high-performance, zero-dependency tool lib for java.
It includes 8 modules:

* <<chapter-dependencies>>: The dependency platform of _fs_;
* <<chapter-annotations>>: Annotations of _fs_, dependents on _fs-jsr305_, can help improve code quality;
* <<chapter-jsr305>>: JSR305 for _fs_, providing partial implementations of _jsr305_ annotations;
* <<chapter-asm>>: Internal asm (7.1) for _fs_, no dependencies;
* <<chapter-core>>: Core module of _fs_, dependents on _fs-annotations_, main part of _fs_;
* <<chapter-all>>: Aggregation of _fs_, including all classes and resources in _fs-jsr305_, _fs-annotations_ and _fs-core_, zero-dependency;
* <<chapter-internal>>: Internal module, typically providing internal classes for tests;
* <<chapter-tests>>: Tests module, benchmarks here;

Note:

* _fs-dependencies_ should be published as a `bom` (`<packaging>pom</packaging>`);
* _fs-jsr305_, _fs-annotations_, _fs-asm_, _fs-core_ and _fs-all_ should be published as jars;
* _fs-internal_ and _fs-tests_ should not be published;

[[chapter-dependencies]]
== _fs-dependencies_

src: link:../fs-dependencies/[fs-dependencies]

_fs-dependencies_ is the dependency platform of _fs_, should be published as a `bom` (`<packaging>pom</packaging>`).

[[chapter-annotations]]
== _fs-annotations_

src: link:../fs-annotations/[fs-annotations]

_fs-annotations_ is the annotation module of _fs_, should be published as a jar.
It depends on _fs-jsr305_.

It contains:

* Annotations for _fs_: such as `space.sunqian.annotations.Nonnull`, `space.sunqian.annotations.Nullable`...;

[[chapter-jsr305]]
== _fs-jsr305_

src: link:../fs-jsr305/[fs-jsr305]

_fs-jsr305_ is the partial jsr305 implementations for _fs_, should be published as a jar.

It contains:

* Partial implementations of jsr305: such as `javax.annotation.Nonnull`, `javax.annotation.Nullable`...;

[[chapter-asm]]
== _fs-asm_

src: link:../fs-asm/[fs-asm]

_fs-asm_ is the internal asm (7.1) for _fs_, should be published as a jar.

It contains core asm classes: such as `ClassReader`, `ClassWriter`, `MethodVisitor`... under `space.sunqian.asm` package.

[[chapter-core]]
== _fs-core_

src: link:../fs-core/[fs-core]

_fs-core_ is main part of _fs_, should be published as a jar.
It depends on _fs-annotations_.

It contains:

* Core utility kits: such as `Fs`, `StringKit`, `IOKit`...;
* Core interfaces: such as `SimpleCache`, `InjectedApp`...;
* Default implementations for core interfaces;

Unless it is necessary to create a separate module, kits, interfaces, and implementations should all be written here.

The codes from `JDK8` to `JDK17` are also written here, and the `build script` will automatically compile into the corresponding version of the class file. `FsLoader` can be used in the code to distinguish between different implementation versions:

[source,java]
----
interface HttpCallerService {

    @Nonnull
    HttpCallerService INST = FsLoader.loadImplByJvm(HttpCallerService.class, 11);

    @Nonnull
    HttpCaller newCaller(
        int bufSize,
        @Nonnull Proxy proxy
    ) throws HttpNetException;
}
----

[[chapter-all]]
== _fs-all_

src: link:../fs-all/[fs-all]

_fs-all_ is the aggregation of _fs-annotations_ and _fs-core_, should be published as a jar.
It aggregates all classes and resources in _fs-jsr305_, _fs-annotations_ and _fs-core_, and zero-dependency for publishing.

This module can not only integrate _fs-jsr305_, _fs-annotations_ and _fs-core_'s classes and resources, but also generate aggregations for `Javadoc`, `Jacoco`, and `test reports`.

[[chapter-internal]]
== _fs-internal_

src: link:../fs-internal/[fs-internal]

_fs-internal_ is the internal module of _fs_, should not be published.
It typically provides internal classes for tests.

[[chapter-tests]]
== _fs-tests_

src: link:../fs-tests/[fs-tests]

_fs-tests_ is the internal tests module of _fs_, should not be published.
It typically provides internal tests such as benchmarks.

image::fs.svg[]