package xyz.sunqian.common.reflect.proxy;

import xyz.sunqian.annotations.Nonnull;

/**
 * The factory to create proxy instance (by {@link #newInstance()}) and provide proxy class (by {@link #proxyClass()}).
 *
 * @author sunqian
 */
public interface ProxyFactory {

    /**
     * Creates and returns a new proxy instance.
     *
     * @param <T> the type of the instance
     * @return a new proxy instance
     * @throws ProxyException if any problem occurs
     */
    <T> @Nonnull T newInstance() throws ProxyException;

    /**
     * Returns the actual proxy class generated by the {@link ProxyMaker}.
     *
     * @return actual proxy class generated by the {@link ProxyMaker}
     */
    @Nonnull
    Class<?> proxyClass();
}
