// package space.sunqian.fs.jdbc;
//
// import space.sunqian.annotation.Nonnull;
// import space.sunqian.annotation.Nullable;
// import space.sunqian.annotation.RetainedParam;
//
// import java.lang.reflect.Type;
// import java.sql.Connection;
// import java.sql.PreparedStatement;
// import java.sql.ResultSet;
// import java.sql.SQLException;
// import java.sql.Statement;
// import java.util.List;
//
// final class PreparedSqlImpl implements PreparedSql {
//
//     private final @Nonnull String sql;
//     private final @Nonnull List<Object> params;
//     private final @Nonnull Connection connection;
//     private @Nullable PreparedStatement preparedStatement;
//
//     PreparedSqlImpl(
//         @Nonnull Connection connection,
//         @Nonnull String sql,
//         @Nonnull @RetainedParam List<Object> params
//     ) {
//         this.connection = connection;
//         this.sql = sql;
//         this.params = params;
//     }
//
//     @Override
//     public @Nonnull String sql() {
//         return sql;
//     }
//
//     @Override
//     public @Nonnull List<Object> parameters() {
//         return params;
//     }
//
//     @Override
//     public <T> @Nonnull SqlQuery<T> query(Type type) throws JdbcException {
//         try {
//             ResultSet resultSet = query();
//             return new SqlQueryImpl<>(resultSet, type);
//         } catch (Exception e) {
//             throw new JdbcException(e);
//         }
//     }
//
//     @Override
//     public @Nonnull ResultSet query() throws JdbcException {
//         try {
//             PreparedStatement stmt = getPreparedStatement();
//             return stmt.executeQuery();
//         } catch (SQLException e) {
//             throw new JdbcException(e);
//         }
//     }
//
//     @Override
//     public @Nonnull SqlUpdate update() throws JdbcException {
//         try {
//             PreparedStatement stmt = getPreparedStatement();
//             int affectedRows = stmt.executeUpdate();
//             return new SqlUpdateImpl(stmt, affectedRows);
//         } catch (SQLException e) {
//             throw new JdbcException(e);
//         }
//     }
//
//     @Override
//     public @Nonnull SqlInsert insert() throws JdbcException {
//         try {
//             PreparedStatement stmt = getPreparedStatement(true);
//             int affectedRows = stmt.executeUpdate();
//
//             // Get auto-generated keys if available
//             java.util.List<Object> autoGeneratedKeys = new java.util.ArrayList<>();
//             try (ResultSet keys = stmt.getGeneratedKeys()) {
//                 while (keys != null && keys.next()) {
//                     autoGeneratedKeys.add(keys.getObject(1));
//                 }
//             } catch (SQLException e) {
//                 // Ignore if auto-generated keys are not supported
//             }
//
//             return new SqlInsertImpl(stmt, affectedRows, autoGeneratedKeys);
//         } catch (SQLException e) {
//             throw new JdbcException(e);
//         }
//     }
//
//     private @Nonnull PreparedStatement getPreparedStatement() throws SQLException {
//         return getPreparedStatement(false);
//     }
//
//     private @Nonnull PreparedStatement getPreparedStatement(boolean returnGeneratedKeys) throws SQLException {
//         if (preparedStatement == null) {
//             if (returnGeneratedKeys) {
//                 preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
//             } else {
//                 preparedStatement = connection.prepareStatement(sql);
//             }
//
//             // Set parameters
//             for (int i = 0; i < params.length; i++) {
//                 preparedStatement.setObject(i + 1, params[i]);
//             }
//         }
//         return preparedStatement;
//     }
//
//     /**
//      * Closes the prepared statement.
//      */
//     public void close() {
//         if (preparedStatement != null) {
//             try {
//                 preparedStatement.close();
//             } catch (SQLException e) {
//                 // Ignore close errors
//             }
//             preparedStatement = null;
//         }
//     }
//
//     private static final class SqlQueryImpl<T> implements SqlQuery<T> {
//
//         private final @Nonnull ResultSet resultSet;
//         private final @Nonnull Type type;
//         private @Nullable PreparedStatement preparedStatement;
//
//         SqlQueryImpl(@Nonnull ResultSet resultSet, @Nonnull Type type) {
//             this.resultSet = resultSet;
//             this.type = type;
//         }
//
//         @Override
//         public @Nonnull ResultSet resultSet() {
//             return resultSet;
//         }
//
//         @Override
//         public @Nonnull Type type() {
//             return type;
//         }
//
//         @Override
//         public @Nonnull Statement statement() {
//             return preparedStatement();
//         }
//
//         @Override
//         public @Nonnull PreparedStatement preparedStatement() {
//             if (preparedStatement == null) {
//                 try {
//                     preparedStatement = (PreparedStatement) resultSet.getStatement();
//                 } catch (Exception e) {
//                     throw new JdbcException("Failed to get prepared statement from result set", e);
//                 }
//             }
//             return preparedStatement;
//         }
//
//         @Override
//         public void close() throws JdbcException {
//             try {
//                 resultSet.close();
//                 if (preparedStatement != null) {
//                     preparedStatement.close();
//                 }
//             } catch (Exception e) {
//                 throw new JdbcException("Failed to close query resources", e);
//             }
//         }
//     }
//
//     // SqlUpdate implementation
//     private static final class SqlUpdateImpl implements SqlUpdate {
//
//         private final @Nonnull PreparedStatement preparedStatement;
//         private final long affectedRows;
//
//         SqlUpdateImpl(@Nonnull PreparedStatement preparedStatement, long affectedRows) {
//             this.preparedStatement = preparedStatement;
//             this.affectedRows = affectedRows;
//         }
//
//         @Override
//         public long affectedRows() {
//             return affectedRows;
//         }
//
//         @Override
//         public @Nonnull Statement statement() {
//             return preparedStatement;
//         }
//
//         @Override
//         public @Nonnull PreparedStatement preparedStatement() {
//             return preparedStatement;
//         }
//
//         @Override
//         public void close() throws JdbcException {
//             try {
//                 preparedStatement.close();
//             } catch (Exception e) {
//                 throw new JdbcException("Failed to close update resources", e);
//             }
//         }
//     }
//
//     // SqlInsert implementation
//     private static final class SqlInsertImpl implements SqlInsert {
//
//         private final @Nonnull PreparedStatement preparedStatement;
//         private final long insertedRows;
//         private final @Nonnull List<@Nonnull Object> autoGeneratedKeys;
//
//         SqlInsertImpl(@Nonnull PreparedStatement preparedStatement, long insertedRows,
//                       @Nonnull List<@Nonnull Object> autoGeneratedKeys) {
//             this.preparedStatement = preparedStatement;
//             this.insertedRows = insertedRows;
//             this.autoGeneratedKeys = java.util.Collections.unmodifiableList(autoGeneratedKeys);
//         }
//
//         @Override
//         public long insertedRows() {
//             return insertedRows;
//         }
//
//         @Override
//         public @Nonnull List<@Nonnull Object> autoGeneratedKeys() {
//             return autoGeneratedKeys;
//         }
//
//         @Override
//         public @Nonnull Statement statement() {
//             return preparedStatement;
//         }
//
//         @Override
//         public @Nonnull PreparedStatement preparedStatement() {
//             return preparedStatement;
//         }
//
//         @Override
//         public void close() throws JdbcException {
//             try {
//                 preparedStatement.close();
//             } catch (Exception e) {
//                 throw new JdbcException("Failed to close insert resources", e);
//             }
//         }
//     }
// }